services:
  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    ports:
      - "8000:8000"
    environment:
      - RAG_OPENAI_API_KEY=${RAG_OPENAI_API_KEY}
      - EMBEDDINGS_PROVIDER=${EMBEDDINGS_PROVIDER}
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL}
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  librechat:
    image: ghcr.io/danny-avila/librechat:latest
    restart: unless-stopped
    ports:
    - "3080:3080"  # Load Balancer가 접근할 수 있도록 포트 노출
    env_file:
      - .env
    volumes:
      - librechat-data:/app/backend/data
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network



volumes:
  librechat-data:
  mongo-data:

networks:
  app-network: